title: lifelog
description: A personal log.
url: "https://abraxasqux.github.io"
baseurl: "/lifelog"
theme: minima
future: true

minima:
  skin: dark

plugins:
  - jekyll-feed

author:
  name: abraxasQ

header_pages:
  - tags/stocks.md
  - tags/ux.md
  - tags/poetry.md
  - tags/notes.md
  - tags/tools.md
  - about.md

exclude:
  - README.md
  - "*.sh"
